# Generated by Django 5.1.3 on 2025-09-04 17:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FairyTale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный идентификатор')),
                ('title', models.CharField(help_text='Введите заголовок сказки (до 255 символов).', max_length=255, verbose_name='Название сказки')),
                ('story', models.TextField(help_text='Введите полный текст сказки.', verbose_name='История')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата автоматически проставляется при добавлении сказки.', verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Сказка',
                'verbose_name_plural': 'Сказки',
                'ordering': ['-created_at'],
            },
        ),
    ]
