# Generated by Django 5.1.3 on 2025-08-21 19:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Уникальный идентификатор задачи', primary_key=True, serialize=False, verbose_name='ID задачи')),
                ('title', models.CharField(help_text='Краткое название задачи (до 255 символов)', max_length=255, verbose_name='Название задачи')),
                ('description', models.TextField(blank=True, help_text='Подробное описание задачи (может быть пустым)', null=True, verbose_name='Описание задачи')),
                ('status', models.CharField(choices=[('created', 'Создано'), ('in_progress', 'В работе'), ('completed', 'Завершено')], default='created', help_text='Текущий статус задачи', max_length=20, verbose_name='Статус задачи')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Время, когда задача была создана', verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['-created_at'],
            },
        ),
    ]
